name: todos
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  provider: ^6.0.2
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.1.10
  fake_async: ^1.3.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  json_serializable: ^6.2.0
  mockito: ^5.1.0
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
